name: Builds, tests & co

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-compiler:
          - "5.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install Dependencies
        run: opam install --deps-only -t -y .

      - name: Test
        run: opam exec -- dune runtest

      - name: Format
        run: opam install ocamlformat && opam exec -- dune build @fmt

  # install-dependencies:
  #   runs-on: ubuntu-latest
  #   needs: setup-ocaml
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Install project dependencies
  #       run: opam install --deps-only -t -y

  # run-tests:
  #   runs-on: ubuntu-latest
  #   needs: install-dependencies
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Run tests
  #       run: dune runtest

  # check-formatting:
  #   runs-on: ubuntu-latest
  #   needs: install-dependencies
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Check formatting
  #       env:
  #         OCAMLFORMAT: "0.26.1"
  #       run: dune build @fmt
